version: '3'

services:
  web:
    build: backend/
    environment: 
      APP_PORT: 8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/user/src/app
      - ./images:/user/src/app/images